CC = g++
CXXFLAGS = -Wall
LDFLAGS = -lopencv_core -lopencv_highgui -lopencv_imgproc

track_doorhandle: track_doorhandle.cpp
	${CC} ${CXXFLAGS} track_doorhandle.cpp $(LDFLAGS) -o track_doorhandle

install:

uninstall:

clean: rm -rf *.o
